version: '3'

services:
  nextjs:
    build:
      dockerfile: ./docker/nextjs/Dockerfile.prod
    restart: unless-stopped
    labels:
      - traefik.http.routers.app_route.rule=Host(`localhost`)
      - traefik.http.routers.app_route.service=app_service
      - traefik.http.services.app_service.loadbalancer.server.port=3000

  solr:
    restart: unless-stopped

  proxy:
    image: traefik:v2.3
    networks:
      - web_proxy
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
