services:
  nextjs:
    build:
      dockerfile: ./docker/nextjs/Dockerfile.dev
    volumes:
      - ./:/srv
    labels:
      - traefik.http.routers.app_route.rule=Host(`localhost`)
      - traefik.http.routers.app_route.service=nextjs
      - traefik.http.services.nextjs.loadbalancer.server.port=3000
    networks:
      - web_proxy

  solr:
    build:
      dockerfile: ./docker/solr/Dockerfile
    # ports:
      # - '8983:8983'
    user: '8983:8983'
    networks:
      - web_proxy

  proxy:
    image: traefik:v2.3
    networks:
      - web_proxy
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web_proxy: