version: '3'

services:
  nextjs:
    build:
      dockerfile: ./docker/nextjs/Dockerfile.prod
    restart: unless-stopped
    # volumes:
    #   - type: bind
    #     source: ./nextjs/public
    #     target: /app/public
    #     read_only: true
