services:
  nextjs:
    build:
      dockerfile: ./docker/nextjs/Dockerfile.dev
    environment:
      - SOLR_HOST=solr
    ports:
      - '3000:3000'
    depends_on:
      - solr

  solr:
    ports:
      - '8983:8983'
    user: '8983:8983'
