version: '3'

services:
  nextjs:
    build:
      dockerfile: ./docker/nextjs/Dockerfile.prod
    extra_hosts:
      - "edit.sta.dnb.de:10.10.14.212"
    #ports:
    #  - '3000:3000'
    networks:
      dnb-wikibase_default:
        aliases:
          - next.svc

  solr:
    build:
      dockerfile: ./docker/solr/Dockerfile
    # ports:
      # - '8983:8983'
    user: '8983:8983'
    networks:
      dnb-wikibase_default:

networks:
  dnb-wikibase_default:
    external: true