FROM node:20-alpine AS dev-stage

RUN apk add --no-cache python3 make g++
RUN apk add --no-cache git
WORKDIR /srv
COPY ./package*.json ./
RUN npm install
COPY . .
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

CMD [ "npm", "dev"]
